username = ""
data = {"players":{}}
fetched = True
fetchTime = 4
pastdata = {}
vectors = {}
posx = 50
posy = 50
oldposx = 0
oldposy = 0
clock = None
screen = None
#url = "http://socket-lightning3105.rhcloud.com/" + "multiplayer/1"
url = "http://127.0.0.1:5000/" + "multiplayer/1"